### ISSUE TITLE
pdbfixer should be noarch

### ISSUE THREAD

**Issue by hadim** [omnia-md/conda-recipes#1072]
It seems to be that pdbfixer is a noarch package (correct if I am wrong). At the moment, a different package is compiled for every python version and platform. Since the last version is rather old, the package has not been built against py38. In consequence it's not possible to install pdbfixer in a py38 env.

 (on a similar note, is that still planned to move omnia to conda forge?)

**Comment by j-wags** [comment]
I'd be happy to build `pdbfixer` as a noarch package, though I'm not really familiar with the codebase, so I hope I'm not missing any details that might prevent it. Any objections, @jchodera or @peastman? 

> (on a similar note, is that still planned to move omnia to conda forge?)

Yes! We've been working on getting all the CUDA packages/build images that we need available, and we're quite close. You can follow progress here: https://github.com/conda-forge/openmm-feedstock

We're hoping to move OpenMM over for the 7.5 release (aiming to get this done before the end of the year!), and all of Omnia will follow after that :-)

**Comment by peastman** [comment]
I think that should be fine.  It depends on OpenMM, which has native code, but PDBFixer itself is pure Python.

> We're hoping to move OpenMM over for the 7.5 release (aiming to get this done before the end of the year!)

I'm hoping for much sooner than that!

**Comment by j-wags** [comment]
I've just verified the [noarch build](https://anaconda.org/omnia/pdbfixer/files) on my mac -- Could I get a second set of eyes before I move the `noarch` package from `omnia/label/rc` to the main `omnia` channel?

```
conda create --yes -n pdbfixer-noarch -c conda-forge -c omnia -c omnia/label/rc pdbfixer nose nose-timer
conda activate pdbfixer-noarch
git clone https://github.com/openmm/pdbfixer.git
cd pdbfixer
cd devtools && nosetests pdbfixer --nocapture --verbosity=2 --with-timer --with-doctest -a '!slow' && cd ..
```

**Comment by hadim** [comment]
System used: Ubuntu 20.10

```bash
$ cd devtools && nosetests pdbfixer --nocapture --verbosity=2 --with-timer --with-doctest -a '!slow' && cd ..
Doctest: pdbfixer.pdbfixer.PDBFixer.__init__ ... ok (0.7787s)
Doctest: pdbfixer.pdbfixer.PDBFixer.addMissingAtoms ... FAIL
Doctest: pdbfixer.pdbfixer.PDBFixer.addMissingHydrogens ... ok (2.1623s)
Doctest: pdbfixer.pdbfixer.PDBFixer.addSolvent ... ok (1.3392s)
Doctest: pdbfixer.pdbfixer.PDBFixer.applyMutations ... FAIL
Doctest: pdbfixer.pdbfixer.PDBFixer.findMissingAtoms ... ok (0.4482s)
Doctest: pdbfixer.pdbfixer.PDBFixer.findMissingResidues ... ok (0.3176s)
Doctest: pdbfixer.pdbfixer.PDBFixer.findNonstandardResidues ... ok (0.3152s)
Doctest: pdbfixer.pdbfixer.PDBFixer.removeChains ... FAIL
Doctest: pdbfixer.pdbfixer.PDBFixer.removeHeterogens ... ok (0.4896s)
Doctest: pdbfixer.pdbfixer.PDBFixer.replaceNonstandardResidues ... ok (0.3654s)
test_build_and_simulate.test_build_and_simulate ... ------------------------------------------------
110D
------------------------------------------------
116D
------------------------------------------------
117D
------------------------------------------------
118D
------------------------------------------------
134D
------------------------------------------------
135D
------------------------------------------------
136D
------------------------------------------------
138D
------------------------------------------------
143D
------------------------------------------------
148D
------------------------------------------------
151D
------------------------------------------------
152D
------------------------------------------------
159D
------------------------------------------------
177D
EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
17RA
------------------------------------------------
183D
------------------------------------------------
184D
------------------------------------------------
186D
------------------------------------------------
187D
EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
188D
EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
189D
EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
1A11
------------------------------------------------
1A13
------------------------------------------------
1A1P
------------------------------------------------
1A3P
------------------------------------------------
1A51
EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
1A60
------------------------------------------------
1A83
------------------------------------------------
1A9L
------------------------------------------------
1AAF
------------------------------------------------
1AB1
------------------------------------------------
1ABZ
------------------------------------------------
1AC7
------------------------------------------------
1ACW
------------------------------------------------
1AD7
EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
1ADX
------------------------------------------------
1AFP
EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
1AFT
------------------------------------------------
1AFX
------------------------------------------------
1AG7
------------------------------------------------
1AGG
EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
1AGL
EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
1AGT
------------------------------------------------
1AHL
------------------------------------------------
1AIE
------------------------------------------------
1AJ1

------------------------------------------------
1AJF
------------------------------------------------
1AJJ
------------------------------------------------
1AJU
------------------------------------------------
1AKG
------------------------------------------------
1AKX
------------------------------------------------
1AL1
------------------------------------------------
1ALE
------------------------------------------------
1ALF
------------------------------------------------
1ALG
EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
1AM0
------------------------------------------------
1AMB
------------------------------------------------
1AMC
------------------------------------------------
1AML
------------------------------------------------
1ANP
------------------------------------------------
1ANR
------------------------------------------------
1ANS

EXCEPTION DURING BUILD
HTTP Error 502: Bad Gateway
------------------------------------------------
1AOO
------------------------------------------------

SUMMARY OF FAILURES:

  177D : HTTP Error 502: Bad Gateway
  187D : HTTP Error 502: Bad Gateway
  188D : HTTP Error 502: Bad Gateway
  189D : HTTP Error 502: Bad Gateway
  1A51 : HTTP Error 502: Bad Gateway
  1AD7 : HTTP Error 502: Bad Gateway
  1AFP : HTTP Error 502: Bad Gateway
  1AGG : HTTP Error 502: Bad Gateway
  1AGL : HTTP Error 502: Bad Gateway
  1ALG : HTTP Error 502: Bad Gateway
  1ANS : HTTP Error 502: Bad Gateway

ERROR
test_cli.test_help ... ok (0.2941s)
test_cli.test_pdbid ... Traceback (most recent call last):
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/bin/pdbfixer", line 6, in <module>
    sys.exit(pdbfixer.pdbfixer.main())
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 1235, in main
    fixer = PDBFixer(pdbid=options.pdbid)
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 258, in __init__
    file = urlopen(url)
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
ERROR
test_cli.test_url ... ok (1.0465s)
test_mutate.test_mutate_1 ... ok (0.8817s)
test_mutate.test_mutate_2 ... ok (1.2434s)
test_mutate.test_mutate_3_fails ... ok (0.4120s)
test_mutate.test_mutate_4_fails ... ok (0.3421s)
test_mutate.test_mutate_5_fails ... ok (0.3518s)
test_mutate.test_mutate_multiple_copies_of_chain_A ... ok (0.5269s)
test_removechains.test_removechain_ids ... ok (4.3718s)
test_removechains.test_removechain_indices ... ok (4.4612s)

======================================================================
ERROR: test_build_and_simulate.test_build_and_simulate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/tests/test_build_and_simulate.py", line 204, in test_build_and_simulate
    raise Exception("Build test failed on one or more PDB files.")
Exception: Build test failed on one or more PDB files.

======================================================================
ERROR: test_cli.test_pdbid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/tests/test_cli.py", line 27, in run_cli
    output = subprocess.check_output('pdbfixer ' + arguments, shell=True)
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'pdbfixer --pdbid 1LE1' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/tests/test_cli.py", line 51, in test_pdbid
    run_cli('--pdbid 1LE1')
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/tests/test_cli.py", line 33, in run_cli
    raise Exception(message)
Exception: An error return value (1) was obtained:

b''


======================================================================
FAIL: Doctest: pdbfixer.pdbfixer.PDBFixer.addMissingAtoms
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 2204, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pdbfixer.pdbfixer.PDBFixer.addMissingAtoms
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 872, in addMissingAtoms

----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 890, in pdbfixer.pdbfixer.PDBFixer.addMissingAtoms
Failed example:
    fixer = PDBFixer(pdbid='2F4J')
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.addMissingAtoms[0]>", line 1, in <module>
        fixer = PDBFixer(pdbid='2F4J')
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 258, in __init__
        file = urlopen(url)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 502: Bad Gateway
----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 891, in pdbfixer.pdbfixer.PDBFixer.addMissingAtoms
Failed example:
    fixer.findMissingResidues()
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.addMissingAtoms[1]>", line 1, in <module>
        fixer.findMissingResidues()
    NameError: name 'fixer' is not defined
----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 892, in pdbfixer.pdbfixer.PDBFixer.addMissingAtoms
Failed example:
    fixer.findMissingAtoms()
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.addMissingAtoms[2]>", line 1, in <module>
        fixer.findMissingAtoms()
    NameError: name 'fixer' is not defined
----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 893, in pdbfixer.pdbfixer.PDBFixer.addMissingAtoms
Failed example:
    fixer.addMissingAtoms()
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.addMissingAtoms[3]>", line 1, in <module>
        fixer.addMissingAtoms()
    NameError: name 'fixer' is not defined


======================================================================
FAIL: Doctest: pdbfixer.pdbfixer.PDBFixer.applyMutations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 2204, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pdbfixer.pdbfixer.PDBFixer.applyMutations
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 726, in applyMutations

----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 751, in pdbfixer.pdbfixer.PDBFixer.applyMutations
Failed example:
    fixer = PDBFixer(pdbid='1VII')
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.applyMutations[0]>", line 1, in <module>
        fixer = PDBFixer(pdbid='1VII')
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 258, in __init__
        file = urlopen(url)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 502: Bad Gateway
----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 752, in pdbfixer.pdbfixer.PDBFixer.applyMutations
Failed example:
    fixer.applyMutations(["ALA-57-GLY"], "A")
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.applyMutations[1]>", line 1, in <module>
        fixer.applyMutations(["ALA-57-GLY"], "A")
    NameError: name 'fixer' is not defined
----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 753, in pdbfixer.pdbfixer.PDBFixer.applyMutations
Failed example:
    fixer.findMissingResidues()
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.applyMutations[2]>", line 1, in <module>
        fixer.findMissingResidues()
    NameError: name 'fixer' is not defined
----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 754, in pdbfixer.pdbfixer.PDBFixer.applyMutations
Failed example:
    fixer.findMissingAtoms()
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.applyMutations[3]>", line 1, in <module>
        fixer.findMissingAtoms()
    NameError: name 'fixer' is not defined
----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 755, in pdbfixer.pdbfixer.PDBFixer.applyMutations
Failed example:
    fixer.addMissingAtoms()
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.applyMutations[4]>", line 1, in <module>
        fixer.addMissingAtoms()
    NameError: name 'fixer' is not defined
----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 756, in pdbfixer.pdbfixer.PDBFixer.applyMutations
Failed example:
    fixer.addMissingHydrogens(7.0)
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.applyMutations[5]>", line 1, in <module>
        fixer.addMissingHydrogens(7.0)
    NameError: name 'fixer' is not defined


======================================================================
FAIL: Doctest: pdbfixer.pdbfixer.PDBFixer.removeChains
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 2204, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pdbfixer.pdbfixer.PDBFixer.removeChains
  File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 534, in removeChains

----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 549, in pdbfixer.pdbfixer.PDBFixer.removeChains
Failed example:
    fixer = PDBFixer(pdbid='4J7F')
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.removeChains[0]>", line 1, in <module>
        fixer = PDBFixer(pdbid='4J7F')
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 258, in __init__
        file = urlopen(url)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 502: Bad Gateway
----------------------------------------------------------------------
File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 550, in pdbfixer.pdbfixer.PDBFixer.removeChains
Failed example:
    fixer.removeChains(chainIndices=[1])
Exception raised:
    Traceback (most recent call last):
      File "/home/hadim/local/conda/envs/pdbfixer-noarch/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest pdbfixer.pdbfixer.PDBFixer.removeChains[1]>", line 1, in <module>
        fixer.removeChains(chainIndices=[1])
    NameError: name 'fixer' is not defined


[error] 80.36% test_build_and_simulate.test_build_and_simulate: 125.8440s
[success] 2.85% test_removechains.test_removechain_indices: 4.4612s
[success] 2.79% test_removechains.test_removechain_ids: 4.3718s
[fail] 2.07% pdbfixer.pdbfixer.PDBFixer.applyMutations: 3.2363s
[fail] 2.01% pdbfixer.pdbfixer.PDBFixer.addMissingAtoms: 3.1423s
[fail] 1.49% pdbfixer.pdbfixer.PDBFixer.removeChains: 2.3313s
[success] 1.38% pdbfixer.pdbfixer.PDBFixer.addMissingHydrogens: 2.1623s
[error] 1.21% test_cli.test_pdbid: 1.8926s
[success] 0.86% pdbfixer.pdbfixer.PDBFixer.addSolvent: 1.3392s
[success] 0.79% test_mutate.test_mutate_2: 1.2434s
[success] 0.67% test_cli.test_url: 1.0465s
[success] 0.56% test_mutate.test_mutate_1: 0.8817s
[success] 0.50% pdbfixer.pdbfixer.PDBFixer.__init__: 0.7787s
[success] 0.34% test_mutate.test_mutate_multiple_copies_of_chain_A: 0.5269s
[success] 0.31% pdbfixer.pdbfixer.PDBFixer.removeHeterogens: 0.4896s
[success] 0.29% pdbfixer.pdbfixer.PDBFixer.findMissingAtoms: 0.4482s
[success] 0.26% test_mutate.test_mutate_3_fails: 0.4120s
[success] 0.23% pdbfixer.pdbfixer.PDBFixer.replaceNonstandardResidues: 0.3654s
[success] 0.22% test_mutate.test_mutate_5_fails: 0.3518s
[success] 0.22% test_mutate.test_mutate_4_fails: 0.3421s
[success] 0.20% pdbfixer.pdbfixer.PDBFixer.findMissingResidues: 0.3176s
[success] 0.20% pdbfixer.pdbfixer.PDBFixer.findNonstandardResidues: 0.3152s
[success] 0.19% test_cli.test_help: 0.2941s
----------------------------------------------------------------------
Ran 23 tests in 157.085s

FAILED (errors=2, failures=3)

```

**Comment by hadim** [comment]
```bash
$ conda list
# packages in environment at /home/hadim/local/conda/envs/pdbfixer-noarch:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2020.11.8            ha878542_0    conda-forge
certifi                   2020.11.8        py37h89c1867_0    conda-forge
cython                    0.29.21          py37hb892b2f_1    conda-forge
fftw3f                    3.3.4                         2    omnia
ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
libblas                   3.9.0                2_openblas    conda-forge
libcblas                  3.9.0                2_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
liblapack                 3.9.0                2_openblas    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
ncurses                   6.2                  h58526e2_3    conda-forge
nose                      1.3.7                   py_1006    conda-forge
nose-timer                1.0.0              pyh8c360ce_0    conda-forge
numpy                     1.19.4           py37h7e9df27_1    conda-forge
openmm                    7.4.2           py37_cuda101_rc_1    omnia
openssl                   1.1.1h               h516909a_0    conda-forge
pdbfixer                  1.6                      py37_0    omnia
pip                       20.2.4                     py_0    conda-forge
python                    3.7.8           h6f2ec95_1_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py37he5f6b98_2    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

**Comment by j-wags** [comment]
Ha! Thanks @hadim :-) 

Looks like some internet connections to the protein data bank failed, and I'm willing to bet that the subsequent failures are due to missing files (since they weren't downloaded). I think this means it's good to switch over.
