### ISSUE TITLE
jenkins binstar uploads not working

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#153]
Not sure if this is a sporadic failure or not:
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/60/consoleFull
```
+ binstar --quiet -t **** upload -u omnia --channel main miniconda/conda-bld/osx-64/assaytools-0.1.0-np18py27_0.tar.bz2 miniconda/conda-bld/osx-64/assaytools-0.1.0-np19py27_0.tar.bz2
Using binstar api site https://api.binstar.org
[SSLError] EOF occurred in violation of protocol (_ssl.c:581) 
Traceback (most recent call last):
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 202, in main
    callback=upload_print_callback(args))
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 423, in upload
    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:581)
 
Traceback (most recent call last):
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/logging/handlers.py", line 861, in emit
    self.socket.send(msg)
error: [Errno 40] Message too long
Logged from file __init__.py, line 13
Build step 'Execute shell' marked build as failure
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Triggering a new build of test-conda-omnia-release-osx
Finished: FAILURE
```

**Comment by kyleabeauchamp** [comment]
I've seen the same EOF violation of protocol before, never fully resolved it.  Possibly sporadic.

**Comment by rmcgibbo** [comment]
We might try updating the root environment to py3. (e.g. miniconda3). We'd still be building the packages in the same build environments (27/33/34), but this would mean that code running in the root env (binstar, conda-build, etc) would be using py3.

From stackoverflow, it looks like a lot of people have encountered `SSLError: EOF occurred in violation of protocol` in varied situations on py2, and I know SSL/TLS has changed a lot in the ~5 years since py2.7 was released, so this could have been fixed already.

It's not a guarantee, just a guess.
