### ISSUE TITLE
Error in jenkins configuration

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#180]
At the end of the build, the jenkins configuration is trying to upload to binstar all files that match `miniconda/conda-bld/*/*.tar.bz2`.

This catches too many things. It includes files inside `miniconda/conda-bld/src_cache/`, if they end in .bz2, which are not conda packages. For example, below it's trying to upload the tarball of the boost source, downloaded from sourcefource (https://github.com/omnia-md/conda-recipes/blob/master/boost/meta.yaml#L6).

```
binstar --quiet -t $BINSTAR_TOKEN upload -u omnia --channel $CHANNEL miniconda/conda-bld/*/*.tar.bz2
```
```
+ binstar --quiet -t **** upload -u omnia --channel main miniconda/conda-bld/osx-64/appdirs-1.4.0-py27_0.tar.bz2 miniconda/conda-bld/osx-64/appdirs-1.4.0-py33_0.tar.bz2 miniconda/conda-bld/osx-64/appdirs-1.4.0-py34_0.tar.bz2 miniconda/conda-bld/osx-64/boost-1.58.0-py27_0.tar.bz2 miniconda/conda-bld/osx-64/openmm-6.2-py27_3.tar.bz2 miniconda/conda-bld/osx-64/openmm-6.2-py33_3.tar.bz2 miniconda/conda-bld/osx-64/openmm-6.2-py34_3.tar.bz2 miniconda/conda-bld/osx-64/pytools-2014.3.5-py27_0.tar.bz2 miniconda/conda-bld/osx-64/pytools-2014.3.5-py33_0.tar.bz2 miniconda/conda-bld/osx-64/pytools-2014.3.5-py34_0.tar.bz2 miniconda/conda-bld/osx-64/silo-4.10.2-0.tar.bz2 miniconda/conda-bld/src_cache/boost_1_58_0.tar.bz2
Using binstar api site https://api.binstar.org
[BinstarError] Could not detect package type of file 'miniconda/conda-bld/src_cache/boost_1_58_0.tar.bz2' please specify package type with option --package-type 
Traceback (most recent call last):
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 164, in main
    package_type = determine_package_type(filename, args)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 69, in determine_package_type
    raise errors.BinstarError('Could not detect package type of file %r please specify package type with option --package-type' % filename)
BinstarError: Could not detect package type of file 'miniconda/conda-bld/src_cache/boost_1_58_0.tar.bz2' please specify package type with option --package-type
```

**Comment by jchodera** [comment]
I've seen this and was wondering what was going on.

Is there a quick fix?

In the longer term, I'd love to switch to a build script that incrementally uploads the package as soon as it has been built.

**Comment by rmcgibbo** [comment]
You need to change the wildcards in your configuration. Make the match more restrictive. e.g. change `miniconda/conda-bld/*/*.tar.bz2` to  `miniconda/{osx-64,linux-64,win-32,win-64}/*.tar.bz2` 

http://unix.stackexchange.com/a/50245

**Comment by jchodera** [comment]
Changed, though from `miniconda/conda-bld/*/*.tar.bz2` to `miniconda/conda-bld/{osx-64,linux-64,win-32,win-64}/*.tar.bz2`

**Comment by jchodera** [comment]
If we wanted to skip this explicit upload step and upload incrementally, do we just need to use
```
conda config --set binstar_upload yes
```
or would this not correctly specify which channel we should upload to?

**Comment by rmcgibbo** [comment]
not sure.

**Comment by jchodera** [comment]
Still tinkering.  Rebuilding now.

**Comment by jchodera** [comment]
Seems to be working.  Please reopen if there are further issues!
