### ISSUE TITLE
AppVeyor issues 

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#242]
There seem to be some errors during AppVeyor execution that don't trigger appveyor to fail:
https://ci.appveyor.com/project/rmcgibbo/conda-recipes/build/1.0.114/job/ftt8ty1d7wnyuj50#L9713
```

Removing old build directory
Traceback (most recent call last):
  File "C:\Python34_64\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Python34_64\lib\site-packages\conda_build\main_build.py", line 127, in main
    args_func(args, p)
  File "C:\Python34_64\lib\site-packages\conda_build\main_build.py", line 349, in args_func
    args.func(args, p)
  File "C:\Python34_64\lib\site-packages\conda_build\main_build.py", line 308, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "C:\Python34_64\lib\site-packages\conda_build\build.py", line 326, in build
    rm_rf(config.short_build_prefix)
  File "C:\Python34_64\lib\site-packages\conda\install.py", line 186, in rm_rf
    shutil.rmtree(path)
  File "C:\Python34_64\lib\shutil.py", line 478, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python34_64\lib\shutil.py", line 368, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34_64\lib\shutil.py", line 368, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34_64\lib\shutil.py", line 368, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34_64\lib\shutil.py", line 373, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python34_64\lib\shutil.py", line 371, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Python34_64\\envs\\_build\\Lib\\site-packages\\markupsafe\\_speedups.pyd'
Package exists on binstar: omnia
  full_name: omnia/omnia/1.0/win-64/omnia-1.0-1.tar.bz2
  uploaded:  2015-04-22 21:46:26.403000+00:00
  md5:       a22e9b41f21ab117782314c7b731607d
Build success
```

**Comment by rmcgibbo** [comment]
Those type of errors (failure to delete a file because it's currently in use, or possibly a race condition in closing the file handle and deleting something) seem to happen a lot on appveyor. I've seen that here, and in other repos.

**Comment by rmcgibbo** [comment]
Same issue as #277, fixed upstream by https://github.com/conda/conda-build/pull/521
