### ISSUE TITLE
appveyor issues

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#277]
Appveyor passes, but this output appeared several times and OpenMM 6.3 was not built and pushed:
```
Removing old build directory
Traceback (most recent call last):
  File "C:\Python34_32\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Python34_32\lib\site-packages\conda_build\main_build.py", line 173, in main
    args_func(args, p)
  File "C:\Python34_32\lib\site-packages\conda_build\main_build.py", line 400, in args_func
    args.func(args, p)
  File "C:\Python34_32\lib\site-packages\conda_build\main_build.py", line 358, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "C:\Python34_32\lib\site-packages\conda_build\build.py", line 330, in build
    rm_rf(config.short_build_prefix)
  File "C:\Python34_32\lib\site-packages\conda\install.py", line 186, in rm_rf
    shutil.rmtree(path)
  File "C:\Python34_32\lib\shutil.py", line 478, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python34_32\lib\shutil.py", line 368, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34_32\lib\shutil.py", line 368, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34_32\lib\shutil.py", line 368, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python34_32\lib\shutil.py", line 373, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python34_32\lib\shutil.py", line 371, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Python34_32\\envs\\_build\\Lib\\site-packages\\markupsafe\\_speedups.pyd'
Package exists on binstar: parmed
  full_name: omnia/parmed/2.0beta3/win-32/parmed-2.0beta3-np19py34_3.tar.bz2
  uploaded:  2015-07-06 04:40:21.309000+00:00
  md5:       21a8908e288b964f13f0833ce22b9913
Package exists on binstar: pdbfixer
  full_name: omnia/pdbfixer/1.1/win-32/pdbfixer-1.1-np19py34_0.tar.bz2
  uploaded:  2015-05-12 19:30:52.771000+00:00
  md5:       02e008da9c4b0eca567ba3da75732d28
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
 
    https://github.com/conda/conda-build/issues
 
Include the output of the command 'conda info' in your report.
 ```

**Comment by rmcgibbo** [comment]
This is fixed upstream in conda-build here: https://github.com/conda/conda-build/pull/521. Should be in the next release soon.
