### ISSUE TITLE
pdbfixer conda package broken?

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-recipes#300]
I'm getting a setuptools error when I try to run pdbfixer from the command line when installed via conda. Can anyone else reproduce this?

```
$ conda create -n pdbfixer-test pdbfixer
Fetching package metadata: ......
Solving package specifications: .............
Package plan for installation in environment /Users/rmcgibbo/miniconda/envs/pdbfixer-test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pdbfixer-1.2               |       np19py27_0         180 KB
    setuptools-18.1            |           py27_0         341 KB
    wheel-0.24.0               |           py27_0          75 KB
    pip-7.1.0                  |           py27_1         1.4 MB
    ------------------------------------------------------------
                                           Total:         1.9 MB

The following NEW packages will be INSTALLED:

    fftw3f:     3.3.4-2
    numpy:      1.9.2-py27_0
    openmm:     6.3-py27_0
    openssl:    1.0.1k-1
    pdbfixer:   1.2-np19py27_0
    pip:        7.1.0-py27_1
    python:     2.7.10-0
    readline:   6.2-2
    setuptools: 18.1-py27_0
    sqlite:     3.8.4.1-1
    tk:         8.5.18-0
    wheel:      0.24.0-py27_0
    zlib:       1.2.8-0

Proceed ([y]/n)? y

Fetching packages ...
pdbfixer-1.2-n 100% |##############################################################################################################| Time: 0:00:01 107.53 kB/s
setuptools-18. 100% |##############################################################################################################| Time: 0:00:03  97.00 kB/s
wheel-0.24.0-p 100% |##############################################################################################################| Time: 0:00:00 101.01 kB/s
pip-7.1.0-py27 100% |##############################################################################################################| Time: 0:00:15  91.09 kB/s
Extracting packages ...
[      COMPLETE      ]|#################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate pdbfixer-test
#
# To deactivate this environment, use:
# $ source deactivate
#

rmcgibbo@MacBook-Pro  ~/projects/papers/rate-matrix/poster (3.4.2)
$ . activate pdbfixer-test
pdbfixer -h
discarding /Users/rmcgibbo/miniconda/envs/3.4.2/bin from PATH
prepending /Users/rmcgibbo/miniconda/envs/pdbfixer-test/bin to PATH

rmcgibbo@MacBook-Pro  ~/projects/papers/rate-matrix/poster (pdbfixer-test)
$ pdbfixer -h
Traceback (most recent call last):
  File "/Users/rmcgibbo/miniconda/envs/pdbfixer-test/bin/pdbfixer", line 9, in <module>
    load_entry_point('pdbfixer==1.2', 'console_scripts', 'pdbfixer')()
  File "/Users/rmcgibbo/miniconda/envs/pdbfixer-test/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "/Users/rmcgibbo/miniconda/envs/pdbfixer-test/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/pkg_resources/__init__.py", line 2681, in load_entry_point
ImportError: Entry point ('console_scripts', 'pdbfixer') not found
```

**Comment by jchodera** [comment]
Appears to have been corrected by #301
