### ISSUE TITLE
SSL error during binstar connections

### ISSUE THREAD

**Issue by marscher** [omnia-md/conda-recipes#320]
Just noticed that hours after the new msmtools release (1.1) there is still no python3 package available.

Hope this will be fixed soon!
Thank you!

**Comment by rmcgibbo** [comment]
take a look at the output of the build machines (links are by the badges on the README of this repo)

**Comment by jchodera** [comment]
Looks like one of those random binstar errors. Last time, I had to delete packages by hand from binstar and then rebuild.  Can you try that @marscher?  Just commit some minor change to trigger rebuild.

**Comment by rmcgibbo** [comment]
Maybe try switching to miniconda3?

**Comment by marscher** [comment]
Thank you very much! Retriggering the build did the job, maybe something like
````n=0
   until [ $n -ge 5 ]
   do
      binstar upload ... && break
      n=$[$n+1]
      sleep 15
   done
```
would make everybody's life easier :+1:

**Comment by rmcgibbo** [comment]
I think it's worth figuring out the actual cause of that SSL error. I suspect it's a python2-only error, and would be fixed by changing the base miniconda running on the build machine to python3.

**Comment by marscher** [comment]
https://stackoverflow.com/questions/14102416/python-requests-requests-exceptions-sslerror-errno-8-ssl-c504-eof-occurred

It is a reported bug in python2.7, so in the meantime I also vote for switching to python3 on the build machine.

**Comment by marscher** [comment]
I think this can be done very easily - Maybe clone the Jenkins job first, try it out and then rename the job, if it succeeds.

**Comment by marscher** [comment]
@jchodera @kyleabeauchamp can you please change the build backend to Python3?

**Comment by jchodera** [comment]
Working on it.

**Comment by jchodera** [comment]
Well, the errors are certainly *different* now.
```
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /home/vagrant/miniconda/conda-bld/linux-64/pyvisfile-2014.1-np18py33_1.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file omnia/pyvisfile/2014.1/linux-64/pyvisfile-2014.1-np18py33_1.tar.bz2 ... 
Using binstar api site https://api.anaconda.org
[SSLError] EOF occurred in violation of protocol (_ssl.c:600) 
Traceback (most recent call last):
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/vagrant/miniconda/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/home/vagrant/miniconda/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/home/vagrant/miniconda/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/binstar_client/commands/upload.py", line 204, in main
    callback=upload_print_callback(args))
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/binstar_client/__init__.py", line 422, in upload
    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
 
Package exists on binstar: pyvisfile
  full_name: omnia/pyvisfile/2014.1/linux-64/pyvisfile-2014.1-np18py27_1.tar.bz2
  uploaded:  2015-04-23 15:57:03.595000+00:00
  md5:       11228be088313d1cfab42fa2cc190e17
Package exists on binstar: pyvisfile
  full_name: omnia/pyvisfile/2014.1/linux-64/pyvisfile-2014.1-np19py27_1.tar.bz2
  uploaded:  2015-04-23 06:50:54.996000+00:00
  md5:       dff4f9524c43fb81bee35e529a212ddb
Traceback (most recent call last):
  File "./conda-build-all", line 311, in <module>
    main()
  File "./conda-build-all", line 90, in main
    execute(args, p)
  File "./conda-build-all", line 303, in execute
    upload_to_binstar(recipe, python, numpy, username=args.upload)
  File "./conda-build-all", line 219, in upload_to_binstar
    raise e
  File "./conda-build-all", line 216, in upload_to_binstar
    check_call(cmd)
  File "/home/vagrant/miniconda/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[not shown]' returned non-zero exit status 1
Build step 'Execute shell' marked build as failure
```

**Comment by jchodera** [comment]
I instead switched back to python2.7-based `miniconda`.  I realized that it hadn't been grabbing the latest version of `miniconda` each time, so this is fixed now.  Seems to have worked.

Please reopen if there is future trouble.

**Comment by marscher** [comment]
Thank you! You can also use the latest symlink provided here: http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh

**Comment by jchodera** [comment]
That actually failed:
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/211/console

Now trying to back up one version at a time...

**Comment by jchodera** [comment]
`Miniconda-3.9.1-MacOSX-x86_64.sh` did the trick.
