### ISSUE TITLE
Travis packages are failing to upload.

### ISSUE THREAD

**Issue by bas-rustenburg** [omnia-md/conda-recipes#642]
The upload portion of the build seems to be failing (though the build is shown as successful). 

https://travis-ci.org/omnia-md/conda-recipes/jobs/175758659

```
Uploading file omnia/openmoltools/0.7.4/linux-64/openmoltools-0.7.4-py27_0.tar.bz2 ... 
Retrying after 5 seconds...
Traceback (most recent call last):
  File "/io/conda-build-all", line 447, in <module>
    sys.exit(main())
  File "/io/conda-build-all", line 119, in main
    return execute(args, p)
  File "/io/conda-build-all", line 432, in execute
    code = build_package(m, python, numpy, args)
  File "/io/conda-build-all", line 370, in build_package
    force=args.force, dev=args.dev)
  File "/io/conda-build-all", line 282, in upload_to_binstar
    raise err
  File "/io/conda-build-all", line 273, in upload_to_binstar
    check_call(cmd)
  File "/anaconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[not shown]' returned non-zero exit status 1
+ true

```

**Comment by jchodera** [comment]
Working on this now.

**Comment by jchodera** [comment]
I haven't been able to resolve this yet.

I revoked and reissued the anaconda cloud token after the security breach, and encoding this as a secure environment variable with `travis encrypt` seems to result in `anaconda upload` hanging waiting on login credentials. I've tried setting the secure environment variable through the UI as well. No luck as of yet.

**Comment by Lnaden** [comment]
I dont think this is still a problem, we can reopen if it is
