### ISSUE TITLE
Trouble with automated build-all.py on Linux vagrant VM with Jenkins

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#65]
The Jenkins build using the Linux vagrant VM dies trying to build docs on OpenMM:
```
gmake[4]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
gmake[4]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
/home/vagrant/miniconda/conda-bld/work/openmm-6.2/docs-source/usersguide/header.rst:: WARNING: document isn't included in any toctree
gmake[5]: *** [OpenMMDeveloperGuide.pdf] Error 1
gmake[4]: *** [latexpdf] Error 2
make[3]: *** [sphinx-docs/developerguide/latex/OpenMMDeveloperGuide.pdf] Error 2
make[3]: *** Waiting for unfinished jobs....
gmake[5]: *** [OpenMMUsersGuide.pdf] Error 1
gmake[4]: *** [latexpdf] Error 2
make[3]: *** [sphinx-docs/userguide/latex/OpenMMUsersGuide.pdf] Error 2
make[2]: *** [docs-source/CMakeFiles/sphinxpdf.dir/all] Error 2
make[1]: *** [docs-source/CMakeFiles/sphinxpdf.dir/rule] Error 2
make: *** [sphinxpdf] Error 2
```
I'm wondering if some prereqs for building the docs are missing here.

**Comment by kyleabeauchamp** [comment]
Here's another issue that I'm having: https://github.com/conda/conda-build/issues/289

Either I'm doing something stupid, or the conda SAT solver is leaking "irrelevant" data between channels / environments.

**Comment by jchodera** [comment]
Ugh, I'm running into more `sphinx` trouble:
```
! LaTeX Error: File `xstring.sty' not found.
```

**Comment by jchodera** [comment]
Looks like that was due to an incomplete texlive installation.  Trying to fix by a second attempt.

I think we're really going to need to use your provisioning script to package up and locally store a new vagrant box for speed, then reprovision this with a quick conda update each time we build

**Comment by jchodera** [comment]
After fixing the `texlive` installation, we have great success!
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/11/console

Here's the complete list of binstar packages for `osx-64` and `linux-64`:
https://binstar.org/organization/omnia/dashboard/channels/jenkins

**Comment by jchodera** [comment]
Here are the remaining issues I noted:
* `cvxpy` with python 2.7 cannot link `liblapack` because it is not present on this vagrant VM.  Perhaps the `lapack` dependency is missing?:
```
BUILD START: cvxpy-0.2.15-np18py27_0
...
building 'base' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
creating build/temp.linux-x86_64-2.7/src/C
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/vagrant/miniconda/envs/_build/include/python2.7 -c src/C/base.c -o build/temp.linux-x86_64-2.7/src/C/base.o
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/vagrant/miniconda/envs/_build/include/python2.7 -c src/C/dense.c -o build/temp.linux-x86_64-2.7/src/C/dense.o
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/vagrant/miniconda/envs/_build/include/python2.7 -c src/C/sparse.c -o build/temp.linux-x86_64-2.7/src/C/sparse.o
gcc -pthread -shared build/temp.linux-x86_64-2.7/src/C/base.o build/temp.linux-x86_64-2.7/src/C/dense.o build/temp.linux-x86_64-2.7/src/C/sparse.o -L/usr/lib -L/home/vagrant/miniconda/envs/_build/lib -lm -llapack -lblas -lpython2.7 -o build/lib.linux-x86_64-2.7/cvxopt/base.so
/usr/bin/ld: cannot find -llapack
collect2: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
...
```
@rmcgibbo has suggested we just automatically build packages (and dependencies) for the omnia 1.0 release, so this will be excluded from that once I get that working.
* The `ecos` tests failed for Python 3.x:
```
TEST START: ecos-1.0.5-py33_0
Fetching package metadata: ...
Solving package specifications: ...............===== testing package: ecos-1.0.5-py33_0 =====
import: u'ecos'
Traceback (most recent call last):
  File "/home/vagrant/miniconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import ecos
  File "/home/vagrant/miniconda/envs/_test/lib/python3.3/site-packages/ecos.py", line 1, in <module>
    import _ecos
ImportError: /home/vagrant/miniconda/envs/_test/lib/python3.3/site-packages/_ecos.cpython-33m.so: undefined symbol: X
```
This might also be excluded by just building primary packages for omnia 1.0.
* Same checkout problems with `pyhmc` as with the `osx` platform:
```
BUILD START: pyhmc-0.1.1-np18py27_0
Fetching package metadata: ...
Solving package specifications: .Initialized empty Git repository in /home/vagrant/miniconda/conda-bld/git_cache/rmcgibbo_pyhmc.git/
Host key verification failed.
```
Again, this won't be included in omnia 1.0, so no big deal here.
* `pymbar` is not Python 3.x compatible (we already know this)

So it looks like we're in pretty good shape!  

@kyleabeauchamp : This may mean we want to switch gears away from your manual building of packages.  Perhaps you could test out the `jenkins` channel?

**Comment by kyleabeauchamp** [comment]
Yeah, at this point it sounds like we can use either approach now.

Do you know why there's no py33 and py34 builds of openmm?

**Comment by jchodera** [comment]
Good catch. 

Looked through the [console logs](https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/11/consoleFull):
```
BUILD START: openmm-6.2-py33_0
Fetching package metadata: ...
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
 |                                                                       |   0%
[1/1                 ] |#################################################| 100%
[1/1                 ] |                                                 |   0%
[1/5                 ] |#########                                        |  20%
[2/5                 ] |###################                              |  40%
[3/5                 ] |#############################                    |  60%
[4/5                 ] |#######################################          |  80%
[5/5                 ] |#################################################| 100%
[      COMPLETE      ] |#################################################| 100%

Hint: the following combinations of packages create a conflict with the
remaining packages:
  - sphinxcontrib-bibtex
  - python 3.3*
BUILD START: openmm-6.2-py33_0
Fetching package metadata: ...
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
 |                                                                       |   0%
[1/1                 ] |#################################################| 100%
[1/1                 ] |                                                 |   0%
[1/5                 ] |#########                                        |  20%
[2/5                 ] |###################                              |  40%
[3/5                 ] |#############################                    |  60%
[4/5                 ] |#######################################          |  80%
[5/5                 ] |#################################################| 100%
[      COMPLETE      ] |#################################################| 100%

Hint: the following combinations of packages create a conflict with the
remaining packages:
  - sphinxcontrib-bibtex
  - python 3.3*
BUILD START: openmm-6.2-py34_0
Fetching package metadata: ...
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
 |                                                                       |   0%
[1/1                 ] |#################################################| 100%
[1/1                 ] |                                                 |   0%
[1/5                 ] |#########                                        |  20%
[2/5                 ] |###################                              |  40%
[3/5                 ] |#############################                    |  60%
[4/5                 ] |#######################################          |  80%
[5/5                 ] |#################################################| 100%
[      COMPLETE      ] |#################################################| 100%

Hint: the following combinations of packages create a conflict with the
remaining packages:
  - sphinxcontrib-bibtex
  - python 3.4*
BUILD START: openmm-6.2-py34_0
Fetching package metadata: ...
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
 |                                                                       |   0%
[1/1                 ] |#################################################| 100%
[1/1                 ] |                                                 |   0%
[1/5                 ] |#########                                        |  20%
[2/5                 ] |###################                              |  40%
[3/5                 ] |#############################                    |  60%
[4/5                 ] |#######################################          |  80%
[5/5                 ] |#################################################| 100%
[      COMPLETE      ] |#################################################| 100%

Hint: the following combinations of packages create a conflict with the
remaining packages:
  - sphinxcontrib-bibtex
  - python 3.4*
```
Is this the same issue you were running into?

**Comment by jchodera** [comment]
Could this be because we're just building packages in arbitrary order?  Perhaps there's a build order that doesn't run into this issue?  Or should packages for each python version be built in a separate VM?

**Comment by kyleabeauchamp** [comment]
This does like similar to the issue I've observed.  Hopefully we'll get some feedback from continuum today.
