### ISSUE TITLE
pymbar recipe is not python 3.x compatible

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#70]
This is a known issue that we may punt on.

**Comment by jchodera** [comment]
`osx` failure on jenkins:
```
BUILD START: pymbar-2.1beta0-np18py33_0
Fetching package metadata: ....
Solving package specifications: .+ /Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/envs/_build/bin/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 136, in <module>
    main()
  File "setup.py", line 132, in main
    setupKeywords = buildKeywordDictionary()
  File "setup.py", line 121, in buildKeywordDictionary
    for key in sorted( setupKeywords.iterkeys() ):
AttributeError: 'dict' object has no attribute 'iterkeys'

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-0.14.0               |       np18py33_0        10.6 MB

The following NEW packages will be INSTALLED:

    numpy:      1.8.2-py33_0     
    openssl:    1.0.1j-4         
    python:     3.3.5-3          
    readline:   6.2-2            
    scipy:      0.14.0-np18py33_0
    setuptools: 7.0-py33_0       
    sqlite:     3.8.4.1-0        
    tk:         8.5.15-0         
    xz:         5.0.5-0          
    zlib:       1.2.7-1          
...
Extracting packages ...
 |                                                                       |   0%
[scipy               ] |#################################################| 100%
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |                                                 |   0%
[sqlite-3.8.4.1-0 /Users/jenkins-slave/workspace/conda-omnia-release] |  |  10%
[zlib-1.2.7-1 /Users/jenkins-slave/workspace/conda-omnia-release] |#     |  20%
[openssl-1.0.1j-4 /Users/jenkins-slave/workspace/conda-omnia-release] |  |  30%
[xz-5.0.5-0 /Users/jenkins-slave/workspace/conda-omnia-release] |###     |  40%
[tk-8.5.15-0 /Users/jenkins-slave/workspace/conda-omnia-release] |###    |  50%
[readline-6.2-2 /Users/jenkins-slave/workspace/conda-omnia-release] |##  |  60%
[python-3.3.5-3 /Users/jenkins-slave/workspace/conda-omnia-release] |##  |  70%
[numpy-1.8.2-py33_0 /Users/jenkins-slave/workspace/conda-omnia-release] ||  80%
[setuptools-7.0-py33_0 /Users/jenkins-slave/workspace/conda-omnia-release] ||  90%
[scipy-0.14.0-np18py33_0 /Users/jenkins-slave/workspace/conda-omnia-release] || 100%
[      COMPLETE      ] |#################################################| 100%
Removing old work directory
Source cache directory is: /Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/conda-bld/src_cache
Found source in cache: v2.1.0-beta.tar.gz
Extracting download
Package: pymbar-2.1beta0-np18py33_0
source tree in: /Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/conda-bld/work/pymbar-2.1.0-beta
Command failed: /bin/bash -x -e /Users/jenkins-slave/workspace/conda-omnia-release-osx-2/conda-recipes/pymbar/build.sh
```

**Comment by rmcgibbo** [comment]
Just change `.iterkeys` to `.keys`...

**Comment by jchodera** [comment]
Thanks!  But that's probably not the only thing preventing 3.x compatibility...

For now, we've decided to punt and not worry about Python 3.x compatibility for an initial release.
