### ISSUE TITLE
binstar error 

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#81]
The latest jenkins `linux` build encountered a binstar error when pushing to the `omnia` channel:
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/14/console
```
+ vagrant ssh --command 'binstar --quiet -t **** upload --force -u omnia --channel main miniconda/conda-bld/*/*.tar.bz2'
Using binstar api site https://api.binstar.org
[warning] Distribution linux-64/cvxpy-0.2.15-np18py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/ecos-1.0.5-py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/ecos-1.0.5-py34_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/ambermini-14.0.1-0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/docopt-0.6.2-py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/docopt-0.6.2-py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/docopt-0.6.2-py34_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/ecos-1.0.5-py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np18py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np18py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np18py34_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np19py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np19py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np19py34_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fftw3f-3.3.3-1.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/jpype1-0.5.7-np18_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/jpype1-0.5.7-np19_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/latexcodec-1.0.1-py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/latexcodec-1.0.1-py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/latexcodec-1.0.1-py34_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/mdtraj-1.2.0-np18py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/mdtraj-1.2.0-np18py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/mdtraj-1.2.0-np18py34_0.tar.bz2 already exists ... removing 
[SSLError] EOF occurred in violation of protocol (_ssl.c:581) 
Traceback (most recent call last):
  File "/home/vagrant/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 203, in main
    callback=upload_print_callback(args))
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 418, in upload
    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:581)
```
Anyone ever seen this before?

**Comment by jchodera** [comment]
Same problem again:
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/15/console
```
+ vagrant ssh --command 'binstar --quiet -t **** upload --force -u omnia --channel main miniconda/conda-bld/*/*.tar.bz2'
Using binstar api site https://api.binstar.org
[warning] Distribution linux-64/cvxpy-0.2.15-np18py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/ecos-1.0.5-py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/ecos-1.0.5-py34_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/ambermini-14.0.1-0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/docopt-0.6.2-py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/docopt-0.6.2-py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/docopt-0.6.2-py34_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/ecos-1.0.5-py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np18py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np18py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np18py34_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np19py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np19py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fastcluster-1.1.13-np19py34_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/fftw3f-3.3.3-1.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/jpype1-0.5.7-np18_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/jpype1-0.5.7-np19_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/latexcodec-1.0.1-py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/latexcodec-1.0.1-py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/latexcodec-1.0.1-py34_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/mdtraj-1.2.0-np18py27_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/mdtraj-1.2.0-np18py33_0.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/mdtraj-1.2.0-np19py27_0.tar.bz2 already exists ... removing 
[SSLError] EOF occurred in violation of protocol (_ssl.c:581) 
Traceback (most recent call last):
  File "/home/vagrant/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 203, in main
    callback=upload_print_callback(args))
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 418, in upload
    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:581)
```

**Comment by kyleabeauchamp** [comment]
I have, not sure what it is.  I solved it previously by either ssl conda
upgrades or relogging in.  Ill try to remember

**Comment by jchodera** [comment]
It worked now:
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/16/console

I wonder if it's just a binstar flakiness issue.
