### ISSUE TITLE
CUDA toolkit now provided via anaconda?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#813]
I just noticed that anaconda now appears to provide packages for [different CUDA toolkit versions](https://anaconda.org/anaconda/cudatoolkit/files).

**Comment by jchodera** [comment]
The [numba version of `cudatoolkit`](https://anaconda.org/numba/cudatoolkit/files) appears to be more up-to-date.

**Comment by peastman** [comment]
Keep in mind that the toolkit isn't much use without the driver.  You can't even compile, since libcuda.so comes with the driver, not the toolkit.

**Comment by jchodera** [comment]
I was under the impression we could use multiple toolkit versions if a recent driver (capable of supporting the most recent toolkit version) was installed. The big complaint we've had from users is that we might have compiled/released OpenMM conda packages against a CUDA version that is not available on their systems. 

Presuming we used a docker build environment with a recent CUDA driver, would it be possible to build several versions of the OpenMM conda package using these toolkit versions (7.5, 8.0, 9.0) and make packages for all three (with appropriate toolkit package dependencies) available that would run on a range of drivers? Presumably, only kernels that support the CUDA toolkit we used to compile would work, but I'm not sure if there is more precise matching of CUDA toolkit x driver x compiled code that needs to happen for this to work.

**Comment by peastman** [comment]
I believe the requirement is that `driver version >= toolkit version`.  So if someone had CUDA 9.0 (both driver and toolkit) installed, but we had compiled against CUDA 8.0, this would let it automatically install the older toolkit.  But it wouldn't help the more common situation where they have an older CUDA version installed.  For example, if they're running on a cluster that has CUDA 7.5, that wouldn't work because the 8.0 toolkit isn't compatible with the 7.5 driver.

That's separate from the question of providing several different OpenMM packages compiled against different CUDA versions.  We could do that either way.  But as far as I know, conda can't detect what driver they have installed, so the user would have to manually specify which version they wanted.

**Comment by emigmo** [comment]
how to install cuda toolkit in anaconda

**Comment by jchodera** [comment]
@emigmo : According to [this page](https://anaconda.org/anaconda/cudatoolkit), you could install the CUDA 8.0 toolkit with
```bash
conda install -c anaconda cudatoolkit==8.0
```

**Comment by Sharuk06** [comment]
try this it will detect your pc specs and install the required toolkits i guess!

conda install -c anaconda cudatoolkit 

https://anaconda.org/anaconda/cudatoolkit

**Comment by fastlater** [comment]
@Sharuk06 @jchodera  I installed the cuda and cudnn packages in my environment I get ImportError: Could not find 'cudart64.80.dll' . If I used conda and not the nvidia website, how do I set the required paths or where to find this dll missing file.

**Comment by jchodera** [comment]
We don't officially support installing CUDA via conda, so this should be considered experimental.  But I'd love to see if we could get this to work.

Can you do a "conda list" and paste all the packages you have installed here? And which platform are you on? Sounds like win?

**Comment by fastlater** [comment]
I created this environment to run a tf code. I installed tf 1.4, cuda 8.0 and cudnn 6.0 using anaconda.
This list of installed packages is as below:

# packages in environment at C:\ProgramData\Anaconda3\envs\tfenv:
#
# Name                    Version                   Build  Channel
bleach                    1.5.0                     <pip>
bokeh                     0.12.14                  py35_0
ca-certificates           2017.08.26           h94faf87_0    anaconda
certifi                   2018.1.18                py35_0    anaconda
click                     6.7              py35h10df73f_0
cloudpickle               0.5.2                    py35_1
cudatoolkit               8.0                           3    anaconda
cudnn                     6.0                           0    anaconda
cycler                    0.10.0           py35hcc71164_0
cython                    0.27.3           py35h82876f0_0
dask                      0.17.1                   py35_0
dask-core                 0.17.1                   py35_0
decorator                 4.2.1                    py35_0
distributed               1.21.1                   py35_0
enum34                    1.1.6                     <pip>
freetype                  2.8              vc14h17c9bdf_0  [vc14]  anaconda
h5py                      2.7.1            py35hb2c3add_0
hdf5                      1.10.1           vc14hb361328_0  [vc14]  anaconda
heapdict                  1.0.0                    py35_2
html5lib                  0.9999999                 <pip>
icc_rt                    2017.0.4             h97af966_0
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
imageio                   2.2.0            py35hcd4b9a4_0
intel-openmp              2018.0.0             hd92c6cd_8
jinja2                    2.10             py35hdf652bb_0
jpeg                      9b               vc14h4d7706e_1  [vc14]  anaconda
libpng                    1.6.32           vc14h5163883_3  [vc14]  anaconda
libtiff                   4.0.8           vc14h04e2a1e_10  [vc14]  anaconda
locket                    0.2.0            py35h0dfcdd0_1
Markdown                  2.6.11                    <pip>
markupsafe                1.0              py35hc253e08_1
matplotlib                2.1.2            py35h016c42a_0
mkl                       2018.0.1             h2108138_4
msgpack-python            0.5.5            py35he980bc4_0
networkx                  2.1                      py35_0
numpy                     1.14.1                    <pip>
numpy                     1.14.1           py35h4a99626_1
olefile                   0.45.1                   py35_0
openssl                   1.0.2n               h74b6da3_0    anaconda
packaging                 16.8             py35h5fb721f_1
pandas                    0.22.0           py35h6538335_0
partd                     0.3.8            py35h894d1e4_0
pillow                    4.2.1            py35hd7da350_0    anaconda
pip                       9.0.1            py35h691316f_4
protobuf                  3.5.1                     <pip>
psutil                    5.4.3            py35hfa6e2cd_0
pycocotools               2.0                       <pip>
pyparsing                 2.2.0            py35hcabcaab_1
pyqt                      5.6.0            py35hd46907b_5
python                    3.5.4               h1357f44_23
python-dateutil           2.6.1            py35h6b299a3_1
pytz                      2018.3                   py35_0
pywavelets                0.5.2            py35h7c47ace_0
pyyaml                    3.12             py35h4bf9689_1
qt                        5.6.2           vc14h6f8c307_12  [vc14]  anaconda
scikit-image              0.13.1           py35hfa6e2cd_1
scipy                     1.0.0            py35h75710e8_0
setuptools                38.5.1                    <pip>
setuptools                38.5.1                   py35_0
sip                       4.18.1           py35h01cbaa7_2
six                       1.11.0           py35hc1da2df_1
six                       1.11.0                    <pip>
sortedcontainers          1.5.9                    py35_0
sqlite                    3.20.1           vc14h7ce8c62_1  [vc14]  anaconda
tblib                     1.3.2            py35hd2cf7e1_0
tensorflow-gpu            1.4.0                     <pip>
tensorflow-tensorboard    0.4.0                     <pip>
tk                        8.6.7            vc14hb68737d_1  [vc14]  anaconda
toolz                     0.9.0                    py35_0
tornado                   4.5.3                    py35_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
Werkzeug                  0.14.1                    <pip>
wheel                     0.30.0           py35h38a90bc_1
wheel                     0.30.0                    <pip>
wincertstore              0.2              py35hfebbdb8_0
yaml                      0.1.7            vc14hb31d195_1  [vc14]  anaconda
zict                      0.1.3            py35hf5542e0_0
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  anaconda

**Comment by fastlater** [comment]
The error is

(tfenv) C:\Program Files (x86)\Python 3.5.2\tensorflow\Master - Mask_RCNN>python
 run.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\
platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\ctypes\__init__.py", line 351, i
n __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模組。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 10, in <module>
    import coco
  File "C:\Program Files (x86)\Python 3.5.2\tensorflow\Master - Mask_RCNN\coco.p
y", line 49, in <module>
    import utils
  File "C:\Program Files (x86)\Python 3.5.2\tensorflow\Master - Mask_RCNN\utils.
py", line 15, in <module>
    import tensorflow as tf
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\__init_
_.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\
__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\
pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\ProgramData\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\
platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_80.dll'. TensorFlow requires that this DLL
 be installed in a directory that is named in your %PATH% environment variable.
Download and install CUDA 8.0 from this URL: https://developer.nvidia.com/cuda-t
oolkit

**Comment by jchodera** [comment]
OK, a few things here:
* This is the issue tracker for the `omnia` channel which does not support either the `cudatoolkit` package (on the `anaconda` channel) or tensorflow. Are you asking for help about using OpenMM or some other package from `omnia`, or just tensorflow?
* The error message you are receiving from tensorflow suggests that the directory containing `cudart64_80.dll` has to be in your `%PATH%`:
```
ImportError: Could not find 'cudart64_80.dll'. TensorFlow requires that this DLL
be installed in a directory that is named in your %PATH% environment variable.
```
I *think* the anaconda channel `cudatoolkit` installs that DLL, but it may not be ending up added to your `%PATH%`, which tensorflow seems to require it. Maybe you can search for where conda installed it and try adding it to your path?
* This tensorflow issue may have some useful information for you: https://github.com/tensorflow/tensorflow/issues/13442
* I'd seek further support in the tensorflow issue tracker: https://github.com/tensorflow/tensorflow/issue

Good luck!

**Comment by aisri** [comment]
Extending the issues with conda installation of cudatoolkit. I dont really see the nvcc binary (or cuda-gdb, nvvp, etc) tools installed when using conda. 
Hope they fix this.

**Comment by jchodera** [comment]
I don't think there's a supported mechanism for installing the CUDA toolkit via conda at this time. The best approach I've seen seems to be pytorch, which uses dummy packages to indicate which version of CUDA you've installed: https://anaconda.org/pytorch/repo

**Comment by nospotfer** [comment]
Summary of steps I've done to install tensorflow-gpu in Ubuntu 18.04 (should work in any Debian-based distro).

1.Install Nvidia driver on a machine with supported Nvidia card.
$ sudo apt update
$ sudo ubuntu-drivers autoinstall
$ sudo reboot
2. You might need to switch to Nvidia GPU from Intel GPU by using

$ sudo prime-select nvidia
$ sudo reboot
3. Install Anaconda with python 3.6.

https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh (Don’t use python 3.7.)

4. Install tensorflow-gpu

$ conda install  tensorflow-gpu==1.11 cudatoolkit==9.0 cudnn==7.1.2 h5py

5. You’re done.

**Comment by BladeSun** [comment]
@nospotfer this works! Thanks very much!
By the way, to specify the cuda version you must reinstall tensorflow-gpu with `cudatoolkit==x.x cudnn==x.x` instead of just run `conda install -c anaconda cudatoolkit=x.x` after the tensorflow is installed.
You could look up in this [link](https://docs.nvidia.com/deploy/cuda-compatibility/index.html) to determine which cuda version you want.

**Comment by jchodera** [comment]
@deama : We haven't yet migrated to installation of the CUDA tookit via `conda`. At this point, you still need to [install the CUDA toolkit following instructions from NVIDIA](https://developer.nvidia.com/cuda-downloads).

**Comment by jchodera** [comment]
Since we last checked, there are now [more `cudatoolkit` packages available on the `anaconda` channel](https://anaconda.org/anaconda/cudatoolkit/files) which might also be of use to us, though this still seems incomplete. If we only need to support the latest versions (9.2 and 10.0, which sounds eminently reasonable!) we can go with [these packages](https://anaconda.org/conda-forge/cudatoolkit-dev/files) that *are* complete, though the PPC version is missing (important for [Summit](https://www.olcf.ornl.gov/summit/)), though we could help contribute [here](https://github.com/conda-forge/cudatoolkit-dev-feedstock).

@peastman: For building nightly development packages of OpenMM, do you think CUDA 9.2 and 10.0 would be sufficient?

**Comment by peastman** [comment]
> For building nightly development packages of OpenMM, do you think CUDA 9.2 and 10.0 would be sufficient?

That seems fine.

**Comment by jchodera** [comment]
> Would following that nvidia guide work for me if I'm on windows using anaconda?

@deama : Yes, that is how we intend it to work for now. Note that the NVIDIA installer will install the CUDA Toolkit at the system level, rather than in anaconda, but the OpenMM package you install via `conda` should find the system CUDA compiler.

**Comment by zeneofa** [comment]
Hi, found my way here via googling. I work on summit/titan where there are cuda or cudatoolkit modules. I am wondering how the cudatoolkit conda package interacts with these. Is the package just a wrapper around the existing libraries, so that path/environment resolution is easier? 

Earlier it is mentioned that the package can be used to get tensorflow up and running on an ubuntu system. how would this translate to an hpc environment with pytorch? Here we do not have sudo, and the gpu's are not accessible at install time (often the gpu nodes are behind a firewall). Also the install paths are non standard and environmental variables are often renamed, how does the package actually find the system CUDA compiler? 

My main reason for asking is 'nccl', titan does not seem to have nccl installed and getting it installed on a cray system is proving challenging. Sometimes getting any thing compiled on cray/power system is challenging, so conda has been a great help.

Sorry for the long post and all the questions.

**Comment by jchodera** [comment]
@zeneofa: We don't yet have access to Summit, but on Titan, you can simply load a CUDA toolkit module (7.5 or 9.2) and then install the corresponding version of OpenMM, where we have built a separate package for each CUDA version (7.5 through 10.0) that can be selected via a conda channel label, e.g.:
```bash
conda install -c conda-forge -c omnia -c omnia/label/cudaXY openmm
```
where `cudaXY` is for CUDA X.Y.

For `tensorflow`, [this comment](https://github.com/omnia-md/conda-recipes/issues/813#issuecomment-436261733) refers to [this blog post](https://medium.com/datadriveninvestor/install-tensorflow-gpu-to-use-nvidia-gpu-on-ubuntu-18-04-do-ai-71b0ce64ebc5), where the [`tensorflow-gpu`](https://anaconda.org/anaconda/tensorflow-gpu) metapackage installs the CUDA toolkit via the [`cudatoolkit`](https://anaconda.org/anaconda/cudatoolkit) package. You can see what the `cudatoolkit` contains by downloading [one of the tarballs here](https://anaconda.org/anaconda/cudatoolkit/files) and unpacking it to see what it contains.

It looks like it doesn't include `nvcc`, but [`nccl`](https://anaconda.org/anaconda/nccl/files) is available through a separate conda install
```bash
conda install nccl
```
though this is only built for a few CUDA versions. Some other versions have been compiled and pushed to anaconda cloud:
https://anaconda.org/search?q=nccl

> My main reason for asking is 'nccl', titan does not seem to have nccl installed and getting it installed on a cray system is proving challenging. Sometimes getting any thing compiled on cray/power system is challenging, so conda has been a great help.

Amen!

**Comment by 1961ned** [comment]
To answer about the error posted by fastlater. I had to install tensorflow outside anaconda and run my programs with visual studio, ran fine.. trying to resolve problem in anaconda now(windows7)

**Comment by whungt** [comment]
@1961ned Is there any update about this problem in anaconda on win7?

**Comment by 1961ned** [comment]
nothing yet

**Comment by Astlaan** [comment]
I installed cudatoolkit (10.0.130) in my computer via anaconda.
However, when I now try to install pycuda (via pip), I still get the following error:

```
 c:\users\me\appdata\local\temp\pip-install-o2935gt0\pycuda\src\cpp\cuda.hpp(14): fatal error C1083: Cannot open include file: 'cuda.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 
```

What's appears to be wrong?
