### ISSUE TITLE
Conflicts with existing packages

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#99]
Have you seen these messages in the `osx` jenkins build?
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/30/console
```
+ binstar --quiet -t **** upload -u omnia --channel main miniconda/conda-bld/broken/repex-dev-py27_0.tar.bz2 miniconda/conda-bld/osx-64/gaff2xml-0.0.0-py33_0.tar.bz2 miniconda/conda-bld/osx-64/gaff2xml-0.0.0-py34_0.tar.bz2 miniconda/conda-bld/osx-64/pybtex-docutils-0.2.0-py27_0.tar.bz2 miniconda/conda-bld/osx-64/pybtex-docutils-0.2.0-py33_0.tar.bz2 miniconda/conda-bld/osx-64/pybtex-docutils-0.2.0-py34_0.tar.bz2 miniconda/conda-bld/osx-64/sphinxcontrib-bibtex-0.3.1-py27_0.tar.bz2 miniconda/conda-bld/osx-64/sphinxcontrib-bibtex-0.3.1-py33_0.tar.bz2 miniconda/conda-bld/osx-64/sphinxcontrib-bibtex-0.3.1-py34_0.tar.bz2
Using binstar api site https://api.binstar.org
[Conflict] file osx-64/pybtex-docutils-0.2.0-py27_0.tar.bz2 already exists for package pybtex-docutils version 0.2.0 
Traceback (most recent call last):
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 203, in main
    callback=upload_print_callback(args))
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 398, in upload
    self._check_response(res)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 155, in _check_response
    raise ErrCls(msg, res.status_code)
Conflict: (u'file osx-64/pybtex-docutils-0.2.0-py27_0.tar.bz2 already exists for package pybtex-docutils version 0.2.0', 409)
 
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
This flags the jenkins run as a failure, but does this mean packages are not actually being uploaded when they should?

Also, isn't the new build script supposed to be not rebuilding recipes that are already present, meaning we shouldn't be seeing conflicts?

**Comment by rmcgibbo** [comment]
Is this with the latest version, or earlier. I think I fixed a bug related to this in https://github.com/omnia-md/conda-recipes/pull/95

**Comment by jchodera** [comment]
Huh. Must have been from earlier.

For some reason, the linux vagrant build has been running since 2.00P EST, 7h45m ago:
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/

It seems to be hung here:
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/23/consoleFull
```
BUILD START: repex-dev-py27_0
Fetching package metadata: ....
Solving package specifications: .
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    curl-7.38.0                |                0         521 KB
    hdf5-1.8.14                |                0         1.8 MB
    libnetcdf-4.3.2            |                1         881 KB
    numpy-1.9.1                |           py27_0         7.7 MB
    scipy-0.14.0               |       np19py27_0        34.6 MB
    netcdf4-1.1.1              |       np19py27_1         1.0 MB
    pandas-0.15.2              |       np19py27_0         9.9 MB
    mdtraj-1.2.0               |       np19py27_0         7.7 MB
    ------------------------------------------------------------
                                           Total:        64.1 MB

The following NEW packages will be INSTALLED:
...
```
after `pandas` is installed.

Terminating manually.

**Comment by kyleabeauchamp** [comment]
Well, we can disable repex anyway.  It's not used for anythign

**Comment by jchodera** [comment]
Maybe this is a good time to just specify the omnia metapackage to
conda-build-all, instead of *?

**Comment by kyleabeauchamp** [comment]
works for me

**Comment by kyleabeauchamp** [comment]
Might have some issues with the topology sort, though

**Comment by rmcgibbo** [comment]
I'm pretty sure there's nothing wrong with the current config. The only issue is that some of the packages don't work for various version of platform/python, and that's fine. I mean, ideally they would work, but if they don't, they don't get uploaded.

**Comment by rmcgibbo** [comment]
The original bug that sparked this gh-issue is already fixed.

**Comment by jchodera** [comment]
Ok!
